### ISSUE TITLE
Times Out on Waiting for Airport Dropdown

### ISSUE THREAD

**Issue by avastu** [oliversong/goes-notifier#2]
![screenshot 2017-01-26 at 3 08 27 pm](https://cloud.githubusercontent.com/assets/8085410/22354268/6d0f7a18-e3d9-11e6-94b4-f092832dfb82.png)
Potentially because there is no dropdown? Using LAX (5180).
![screenshot 2017-01-26 at 3 09 38 pm](https://cloud.githubusercontent.com/assets/8085410/22354296/84aeff72-e3d9-11e6-9fa1-1b266eb9440e.png)
:

**Comment by kmonty** [comment]
I found that issue as well. The select list was changed to a radio list. Here is a patch.

[issue-2-goes-select-changed-to-radio-comment-1.patch.txt](https://github.com/oliversong/goes-notifier/files/743379/issue-2-goes-select-changed-to-radio-comment-1.patch.txt)

**Comment by avastu** [comment]
Hi @kmonty! I can confirm this patch works. Thank you!

**Comment by oliversong** [comment]
Thanks for reporting! You're right- the site changed. I've updated with a workaround.
